import { NextResponse, type NextRequest } from "next/server";
import {
  LOCALE_COOKIE,
  defaultLocale,
  isLocale,
  locales,
  matchLocale,
  type Locale,
} from "@/lib/i18n";

/**
 * Language routing. (`proxy` is the Next 16 name for what used to be
 * `middleware`; the old convention is deprecated.)
 *
 * English is served from the apex — "/" and "/work/…" — while the other
 * languages are prefixed. Internally every page lives under /[locale], so an
 * unprefixed path is *rewritten* onto /en rather than redirected: the apex
 * keeps answering 200 with real HTML, which is what curl, crawlers and LLM
 * agents get. Only a reader arriving at "/" whose browser asks for pt or es is
 * redirected; deep links are never hijacked.
 *
 * The chosen language is remembered here, server-side, rather than by a script
 * in the page — so it works with JavaScript disabled.
 */

const YEAR_IN_SECONDS = 60 * 60 * 24 * 365;

function remember(
  response: NextResponse,
  locale: Locale,
  request: NextRequest,
): NextResponse {
  response.cookies.set(LOCALE_COOKIE, locale, {
    path: "/",
    maxAge: YEAR_IN_SECONDS,
    sameSite: "lax",
    httpOnly: true,
    secure: request.nextUrl.protocol === "https:",
  });
  return response;
}

function savedLocale(request: NextRequest): Locale | null {
  const value = request.cookies.get(LOCALE_COOKIE)?.value;
  return value && isLocale(value) ? value : null;
}

/** Which prefix, if any, this path already declares. */
function prefixOf(pathname: string): Locale | null {
  for (const locale of locales) {
    if (pathname === `/${locale}` || pathname.startsWith(`/${locale}/`)) {
      return locale;
    }
  }
  return null;
}

export function proxy(request: NextRequest): NextResponse {
  const { pathname } = request.nextUrl;
  const prefix = prefixOf(pathname);

  // An explicit "/en…" is a request to switch to English. Save it, then send
  // the reader to the canonical English URL, which is unprefixed. Without
  // this, the English flag pointed at "/", the apex honoured the saved
  // language, and English was unreachable from inside the site.
  if (prefix === defaultLocale) {
    const url = request.nextUrl.clone();
    url.pathname = pathname.slice(`/${defaultLocale}`.length) || "/";
    return remember(NextResponse.redirect(url, 307), defaultLocale, request);
  }

  // A prefixed page in another language: serve it, and remember the choice
  // when it actually changed.
  if (prefix) {
    const response = NextResponse.next();
    return savedLocale(request) === prefix
      ? response
      : remember(response, prefix, request);
  }

  if (pathname === "/") {
    const locale = savedLocale(request) ?? matchLocale(request.headers.get("accept-language"));

    if (locale !== defaultLocale) {
      const url = request.nextUrl.clone();
      url.pathname = `/${locale}`;
      // 307, not 301: the destination depends on the reader, so it must never
      // be cached as if it were the one true answer for this URL.
      const redirect = NextResponse.redirect(url, 307);
      redirect.headers.append("Vary", "Accept-Language");
      redirect.headers.append("Vary", "Cookie");
      return redirect;
    }

    const url = request.nextUrl.clone();
    url.pathname = `/${defaultLocale}`;
    return NextResponse.rewrite(url);
  }

  // Any other unprefixed path is an English URL (e.g. /work/cortefilme).
  const url = request.nextUrl.clone();
  url.pathname = `/${defaultLocale}${pathname}`;
  return NextResponse.rewrite(url);
}

export const config = {
  // Skip Next internals and anything that is not a page. The icon routes are
  // listed explicitly: they are generated by app/icon.tsx and app/apple-icon.tsx
  // and have NO file extension, so the trailing "looks like a file" rule does
  // not catch them — without this they were rewritten to /en/icon and 404'd.
  matcher: [
    "/((?!_next/|api/|icon$|apple-icon$|opengraph-image$|favicon\\.ico|sitemap\\.xml|robots\\.txt|manifest\\.webmanifest|llms\\.txt|.*\\.[\\w]+$).*)",
  ],
};
